baseurl = "http://rs.luminousspice.com"
languageCode = "ja"
title = "the Right Stuff"
author = "luminosspice"
theme = "lanyon"
paginate = 5
paginatePath ="p"
canonifyurls = true
hasCJKLanguage = true
googleAnalytics = "UA-29141274-4"

[permalinks] 
	post = "/:filename/"
	article = "/:section/:filename/"
	page = "/:section/:filename/"

[taxonomies]
	tag = "tags"
	category = "categories"
	anki = "anki"

[params]
	description = "このコンテンツは @luminousspice が非同期的に更新しています。経時的な順序に意味はありません。"
	topitem = 5
	author = "luminosspice"
	githubName = "luminosspice"
	twitterName = "luminosspice"
	siteImage = "/apple-touch-icon.png"
	twitterCardImage = "/apple-touch-icon.png"
	feeditem = 5
#laynon
	Tagline = ""
	DateForm = "2006-01-02"

[params.github]
	url = "http://github.com/luminousspice/"

[[menu.main]]
	name = "総目次"
	url = "/table-of-contents/"
	weight = -200
[[menu.main]]
	name = "Anki 索引"
	url = "/index-how-to-anki/"
	weight = -180
[[menu.main]]
	name = "アーカイブ"
	url = "/post/"
	weight = -170
[[menu.main]]
	name = "全文検索"
	pre = "<i class='fa fa-bullhorn'></i>"
	url = "/search/"
	weight = -160
