---
slug: "anki-fail-to-sync"
date: "2013-11-21T16:17:56+00:00"
lastmod: "2016-04-28T10:59:17+00:00"
title: "Ankiが同期できない問題について"
weight: 10
categories: ["Anki"]
tags: ["Anki","AnkiWeb","AnkiMobile","iOS","iPad","iPhone","iPod touch"]
anki: ["AnkiMobile","AnkiWeb","プロファイル","同期"]
excerpt: "Anki と AnkiWeb の同期の問題をまとめました。プロキシ認証の設定、Anki のバージョン、複数のプロファイルや機器からのアクセス、サポートからのよく回答のあるセキュリティソフトの設定、AnkiWeb の障害情報の入手方法を取り上げます。"
---
= Ankiが同期できない問題について
:author: luminousspice
:lang: ja
:encoding: UTF-8
:keywords:
:description: Anki と AnkiWeb の同期の問題をまとめました。プロキシ認証の設定、Anki のバージョン、複数のプロファイルや機器からのアクセス、サポートからのよく回答のあるセキュリティソフトの設定、AnkiWeb の障害情報の入手方法を取り上げます。

////
http://rightstuff.luminousspice.com/anki-fail-to-sync/
////

{description}

== 設定の再確認

Anki と AnkiWeb との同期で最初につまづく原因は、AnkiWeb のアカウント作成の失敗していること、Anki や連携して使用する AnkiMobile や AnkiDroid の設定が正しく行われていないことです。

設定方法に不安な方は、link:/how-to-sync-with-ankiweb/[AnkiWeb 同期機能の使い方]で確認してください。

== プロキシ認証の失敗 (Mac OS X および Windows)

2014/04/23 更新の link:http://ankisrs.net/docs/manual.html#proxies[Anki Manual Proxies]によれば、Mac OS X および Windows 版の Anki ではツールキットの原因で、システム設定からユーザー名とパスワードの取得ができずプロキシ認証に失敗するとのことです。
このため、Anki を認証が必要なプロキシ経由で同期するには、環境変数 HTTP_PROXY の設定が必要です。

.設定値の一例
----
http://user:pass@proxy.example.com:8080
----

その際にユーザー名やパスワードに @ を使用している場合には、%40 で置き換える必要があります。

.ユーザー名に@が入っている場合
----
http://user%40workspace:pass@proxy.example.com:8080
----

Mac OS X および Windows ともにそれぞれのバージョンによって環境変数の設定方法が異なります。お使いになっている環境に適した方法で設定ください。

== 同期に必須なバージョン

Anki サポートサイトの告知、link:https://anki.tenderapp.com/discussions/announcements/60-anki-and-heartbleed[Anki and Heartbleed] によれば、Heartbleed 問題の対応のため、AnkiWeb と同期して Anki を使い続けるには、Anki 2.0.24 以降に変更になりました。

=== Mac OS X 10.5, 10.6 用代替ビルドを使用している場合

Anki サポートサイト Knowledge Base link:https://anki.tenderapp.com/kb/problems/syncing-errors-with-older-macs[Syncing errors with older Macs] によれば、Anki 2.0.30 が必須になりました。

== 同期中にタイムアウトが発生する場合

link:/changeinanki2/#_%E5%A4%89%E6%9B%B4%E7%82%B9_2_0_31[Anki 変更履歴]によれば、Anki 2.0.31 では、定期的に大量のデータを同期した場合に発生するタイムアウトの問題を解決しています。

== ファイル容量制限

ファイル容量が 100MB を超えるファイルをアップロードすることは出来ません。サーバーエラーが発生します。

Anki 2.0.29 Beta 2 (Sep 15) 以降では、100MB を超えるファイルは同期対象外になります。

== 複数のプロファイルを使用している場合

AnkiWeb の特定のアカウントに、特定の機器からは一つのプロファイルだけが接続できます。

一つの機器で複数のプロファイルを使っている場合、認証済みのプロファイルを認証解除して、アクセスしたいプロファイルに変更して認証し直します。

== 複数の機器からアクセスする場合

一つのアカウントに同時に複数の機器からアクセスすることはできません。

それぞれの機器から順番にアクセスしてください。また、同期中の機器がないか確認してみてください。

== サポートからのよくある回答

Anki のサポートサイトで AnkiWeb の接続障害にする質問に対する、よくある回答は
アンチウィルス、ファイアウォールなどのセキュリティソフトの設定、VPN ソフトの設定、ISP によるフィルタリングを原因として指摘しています。

セキュリティソフトの例外設定のために、Anki の再インストールを勧めている場合もあります。
また、古いバージョンの Anki を使用していることを指摘されることも多いです。

サポートサイトへ質問する前に、これらの項目を事前に確認しておくと良いでしよう。

== AnkiWeb の障害情報

Anki と同期する AnkiWeb に障害発生により、同期に失敗したり遅延したりする場合があります。

最新情報の確認は、Anki サポートサイトのlink:https://anki.tenderapp.com/discussions/announcements[Announcements]の告知をご覧下さい。

Anki サポートサイトのlink:https://anki.tenderapp.com/discussions/ankiweb[AnkiWeb]カテゴリでは、AnkiWebについて障害報告したり、他のユーザーからの報告を読むことができます合わせてご利用ください。

=== 主な障害情報の履歴

==== 2015/02/26

AnkiWeb サーバーにパフォーマンス上の問題が発生していましたが、2015/03/02 に最終的な復旧報告がありました。

Anki サポート情報:

. link:https://anki.tenderapp.com/discussions/announcements/80-ankiweb-performance-updates[AnkiWeb performance updates] (2015/03/02)
. link:https://anki.tenderapp.com/discussions/ankidesktop/12070-slow-to-synchronise-last-few-days-could-you-check-it-for-me[Slow to synchronise last few days - could you check it for me?] (2015/03/01)
. link:https://anki.tenderapp.com/discussions/ankiweb/928-ankiweb-too-busy-right-now[AnkiWeb too busy right now] (2015/02/26)

==== 2014/09/16

数時間にわたって発生していたサーバーのメンテナンスエラーが、6時40分過ぎに復旧しました。
Anki サポート情報: link:https://anki.tenderapp.com/discussions/ankiweb/721-ankiweb-maintenance[AnkiWeb maintenance?]

==== 2014/04/04

数日前から発生していた AnkiWeb サーバーに発生していたパフォーマンス上の問題を、サーバーのアップグレードで解決しました。
Anki サポート情報: link:https://anki.tenderapp.com/discussions/announcements/58-ankiweb-servers-upgraded[AnkiWeb servers upgraded]

==== 2013/11/21

13時頃から、AnkiWeb サーバーにネットワーク上の問題が発生し、Anki クライアントアプリケーションとの同期ができなくなっていましが、16時20分過ぎに復旧しました。
Anki サポート情報: link:https://anki.tenderapp.com/discussions/announcements/40-ankiweb-problems-again[AnkiWeb Problems Again]

== Anki の同期に関する修正履歴

link:/changeinanki2/[Anki 2 の変更点 日本語訳]では、これまで Anki に行った修正点を一覧することができます。同期に関する修正内容を確認することができます。

== AnkiMobile 固有の問題

iOS アプリ link:https://geo.itunes.apple.com/jp/app/ankimobile-flashcards/id373493387?mt=8&at=11lGoS[AnkiMobile Flashcards] の過去のバージョンが原因で発生した問題点を紹介します。

=== 同期中にクラッシュ

AnkiMobile 2.0.14 では、AnkiMobile 2.0.13 へ以前のバージョンからアップグレードすると、多数のメディアファイルを同期した場合にアプリケーションがクラッシュする問題を解決しました。

参考情報: Anki サポート Knowledge Base link:https://anki.tenderapp.com/kb/problems/ankimobile-2013-may-crash-when-syncing[AnkiMobile 2.0.13 may crash when syncing] 

=== 不要な完全同期を求めるメッセージ

AnkiMobile 2.0.15 では、不要な場合にも完全同期を促すメッセージを表示する問題を修正しました。

参考情報: AnkiMobile サポートフォーラム link:https://anki.tenderapp.com/discussions/ankimobile/2117-deck-needs-total-upload-download-all-the-time[Inconsistent state upload/download messages]

=== AnkiMobile の同期に関する修正履歴

AppStore の link:https://geo.itunes.apple.com/jp/app/ankimobile-flashcards/id373493387?mt=8&at=11lGoS[AnkiMobile Flashcards] ページにおいて、これまで AnkiMobile に行った修正履歴を一覧することができます。同期に関する修正内容を確認することができます。

== 更新情報

2013/11/21: 初出

2014/04/24: 追加: プロキシ認証失敗、必須条件 2.0.24 以上

2014/09/08: 追加: 複数のプロファイルや機器からの接続、サポートからのよくある回答

2014/09/11: 追加: AnkiDroid 固有の問題

2014/09/15: 追加: ファイル容量制限

2014/10/19: 追加: Anki 2.0.30、2.0.31 の変更点

201M/10/30: 追加: AnkiMobile 2.0.13 が同期中にクラッシュする問題

2014/11/11: 追加: AnkiMobile 2.0.14 の変更点、AnkiDroid の必須バージョン

2014/11/12: 追加: AnkiMobile 2.0.15 の変更点

2015/02/26: 追加: AnkiWeb 処理能力の問題

2015/03/02: 更新: AnkiWeb 処理能力の問題

2016/04/28: 更新: AnkiMobile 2.0.21 対応
