---
slug: "install_anki"
date: "2013-09-29T18:00:18+00:00"
lastmod: "2016-04-27T07:12:23+00:00"
title: "Ankiのインストール"
weight: 30
categories: ["Anki"]
tags: ["Anki"]
anki: ["AnkiDroid","AnkiMobile","AnkiWeb","アンインストール","インストール","ダウンロード","メンテナンス"]
excerpt: "最新 Anki 2.0.36 対応。Anki (OS X, Windows, Linux/BSD) のダウンロードとインストール、アンインストールの方法を説明します。iOS アプリと Android および Chromebook 用アプリは入手先を紹介します。"
---
= Ankiのインストール
:author: luminousspice
:lang: ja
:encoding: UTF-8
:keywords:
:description: 最新 Anki 2.0.36 対応。Anki (OS X, Windows, Linux/BSD) のダウンロードとインストール、アンインストールの方法を説明します。iOS アプリと Android および Chromebook 用アプリは入手先を紹介します。

////
http://rightstuff.luminousspice.com/install_anki/
////

{description}

== Anki のダウンロードとインストール

Anki は、デスクトップ PC 版とモバイルデバイス版では入手場所が異なります。
またデスクトップ PC 版は、 OS 毎にダウンロードファイルが異なります。

デスクトップ PC 版は、link:http://ankisrs.net/[Anki サイト]からアプリケーションをローカルにダウンロードしてインストールします。

モバイルデバイス版は、iOS 版 AnkiMobile は iTunes App Store、Android 版 Ankidroid は Google Play よりインストールします。

この記事では、デスクトップ版のダウンロード先とインストール方法、モバイルデバイス版の入手先について紹介します。

*注意*: 

* この記事の作成時のデスクトップ版の最新バージョンは、Anki 2.0.36 です。今後のアップグレードで、URLやファイル名が変更になる可能性があります。
* デスクトップ版を AnkiWeb サーバーとデータを同期する場合は、Anki 2.0.24 以降が必須です。

== デスクトップ PC の場合

デスクトップ PC 版はダウンロードファイルは別々ですが、一つのプロジェクトとして開発していて OS は違ってもドキュメントは共通です。

* Anki1 からアップグレードする場合は、link:/changeinanki2/#v2[Anki2の変更点]をアップグレードの前に確認しておくことをお勧めします。
* 前回の記事、link:/anki_reset/[Ankiと初期化]では Anki の環境設定の初期化、クリーンインストールする際の注意点をまとめています。
* link:http://ankisrs.net/download/mirror/[最新版以外のアプリケーションを含むアーカイブ]


=== OS X へインストール

. 起動中の Anki があれば終了します。
. link:http://ankisrs.net/#mac[ダウンロードページ]より[Download Anki for Mac]ボタンを押し、`anki-2.0.36.dmg` をダウンロードします。
. ダウンロードした dmg ファイルを開き、Anki ファイルをアプリケーションフォルダーかデスクトップにドラッグしてコピーします。
. コピーしたファイルを開くと Anki は起動します。

*注意*: 

* OS X 版 Anki をお使いになるには、OS X 10.7 以降の Intel Mac が必要です。
* OS X 10.5、10.6 Intel ユーザーのために代替バージョン (Alternate Version) を用意しています。link:http://ankisrs.net/#mac[ダウンロードページ]の[Alternate Version]というリンクをクリックして入手できます。ダウンロードファイルは `anki-2.0.36.qt47.dmg` です。

=== Windows へインストール

. link:http://ankisrs.net/#windows[ダウンロードページ]より[Download Anki for Windows]ボタンを押し、`anki-2.0.36.exe` をダウンロードします。
. `anki-2.0.36.exe` をダブルクリックしてインストーラーを実行します。
. デスクトップ上の Anki のショートカットアイコンをダブルクリックすると、Anki は起動します。

.高 DPI ディスプレイを使用する場合の参考情報
link:https://support.microsoft.com/ja-jp/kb/2900023[一部のデスクトップ アプリケーションが高 DPI ディスプレイでぼやけて表示される]

=== Ubuntu/Debian へインストール

. link:http://ankisrs.net/#linux[ダウンロードページ]より[Download Anki for Ubuntu/Debian]ボタンを押し、`anki-2.0.36.deb` をダウンロードします。
. お使いになっているシステムのパッケージマネージャーを使ってダウンロードした deb ファイルをインストールします。

*注意*: Anki サイトで提供しているバージョンに比べて、Ubuntu/Debian の正式リポジトリに含まれている配布パッケージのバージョンは古いため、Anki サイトから直接アプリケーションを入手することをお勧めします。

=== Fedora へインストール

`sudo yum install anki` を実行するだけでインストールできます。

=== その他の Linux/BSD システムへインストール

. link:http://ankisrs.net/#linux[ダウンロードページ]より[Download Anki Source]ボタンを押し、`anki-2.0.36.tgz` をダウンロードします。
. ダウンロードした tarball(tgz) を解凍し、`README` ファイルに記載している指示に従ってインストールします。

== Anki のアンインストール

Anki のアンインストールをするには、Anki のアプリケーション本体と Anki フォルダー `Documents/Anki/` を削除します。
Anki フォルダーに含まれている単語帳、学習履歴、ユーザープロファイル、バックアップファイルも削除されます。

== モバイルデバイスの場合

モバイルデバイス版のアプリケーションは iOS と Android でそれぞれ別々のプロジェクトで開発しています。
名称も異なり、iOS 版は AnkiMobile、Android 版は AnkiDroid です。

必ずしも PC 版と同じ機能が使える訳ではありません。また、バージョン番号も一致していません。

ドキュメントもそれぞれ独自に作成しており、デスクトップ PC 版のドキュメントがそのまま使える訳ではないことに注意してください。

=== iOS 端末 (iPod Touch, iPad, iPhone) へ AnkiMobile をインストール

Anki の iOS アプリ AnkiMobile は有料アプリケーションです。
このアプリケーションを購入すると、将来のAnkiの開発を支援することができます。

AnkiMobile は、link:https://itunes.apple.com/jp/app/ankimobile-flashcards/id373493387?mt=8&amp;uo=4&amp;at=11lGoS[iTunes App Store] から購入できます。

なお、Web 版の link:https://ankiweb.net/[AnkiWeb] は、無料で利用できます。

* link:/ankimobile-survival-guide/[iPhone ユーザーのための AnkiMobile サバイバルガイド]
* link:/how-to-use-ankimobile/[iPhone ユーザーのためのはじめての Anki]

=== Android 端末へ AnkiDroid をインストール

AnkiDroid (アンキドロイド) は、Anki の開発者 Damien Elmes とは独立したユーザーコミュニティが独自に開発している無償のアプリケーションです。

AnkiDroid は、link:https://play.google.com/store/apps/details?id=com.ichi2.anki[Google Play]から入手できます。

* link:https://ankidroid.org/docs/manual-ja.html[AnkiDroid 2.5 マニュアル]

=== Chromebook へ AnkiDroid をインストール

AnkiDroid 2.4 以降で Chromebook がサポートされています。

AnkiDroid は、link:https://chrome.google.com/webstore/detail/ankidroid/ckmbkodkbmkmdjdimeiddeljndcneifo[Chrome ウェブストア]から入手できます。

=== その他の端末

その他の端末には専用のクライアントソフトはありませんが link:https://ankiweb.net/[AnkiWeb]が利用できます。
link:http://ankisrs.net/#other[Ankiサイト]の　Download Anki 項目の Other タブの内容をご覧ください。
このページでは、携帯電話、Blackberry 端末、Maemo、Windows Phone/Windows Mobile/Windows RT、ニンテンドーDS、Sony PSP、Palm端末の情報を掲載しています。

* Knowledge Base link:https://anki.tenderapp.com/kb/anki-ecosystem/windows-phone-windows-rt[Windows Phone & Windows RT]

== さっそく Anki を使ってみよう

インストールしてどこから手をつけたら良いか分からない方には、link:/how-to-anki/[はじめてのAnki - まず使ってみる]をお勧めします。デスクトップPC版を例にして、Ankiの使い方の基本的な流れが体験できます。

== 更新情報

2013/09/29: 初出

2014/04/13: Anki 2.0.24 からの提供ファイルの変更に対応

2014/04/24: Anki 2.0.26 リリースへの対応

2014/09/22: Anki 2.0.29 リリースへの対応

2015/01/15: AnkiDroid 日本語マニュアル、Anki 2.0.31 リリースへの対応

2015/01/29: AnkiDroid の Chromebook サポートへの対応

2015/04/27: Anki 2.0.36 リリースへの対応
