---
slug: "shared-deck-list-in-japanese"
date: "2015-02-15T05:00:57+00:00"
type: "datatable"
lastmod: "2016-04-18T10:47:59+00:00"
title: "日本語ユーザーのための Anki 共有単語帳リスト"
weight: 30
categories: ["Anki"]
tags: ["Anki","Anki 単語帳","Data","iOS","iPad","iPhone","iPod touch","検索","APKG"]
anki: ["AnkiMobile","共有単語帳"]
excerpt: "日本語ユーザーが利用可能な Anki 共有単語帳を独自に収集し、検索画面を作成しました。 共有単語帳の日本語分類表を使って、詳しく調べることもできます。"
---
= 日本語ユーザーのための Anki 共有単語帳リスト
:author: luminousspice
:lang: ja
:encoding: UTF-8
:keywords:
:description: 日本語ユーザーが利用可能な Anki 共有単語帳を独自に収集し、検索画面を作成しました。 共有単語帳の日本語分類表を使って、詳しく調べることもできます。

////
http://rightstuff.luminousspice.com/?p=2483
////

{description}

== 日本語の共有単語帳を見つけやすく

link:https://ankiweb.net/shared/decks/[AnkiWeb に登録されている単語帳一覧]は、登録数の多い英語表記の単語帳に限定されています。日本語の情報を見つけるには検索する以外に表示する方法がありません。

独自に AnkiWeb の内容を検索閲覧し、日本人にとって利用可能な単語帳をまとめ、検索画面を作りました。

== 共有単語帳検索

[[decklist]]

[frame="topbot",format="csv",grid="rows",cols="2,1,2",options="header",role="table table-striped table-bordered  table-hover"]
|===================================================
題名,分類,タグ
https://ankiweb.net/shared/info/206033178[Ankiの基礎知識], 科学技術, Tips 用語 ショートカット
https://ankiweb.net/shared/info/810249417[Speech Text template for iOS (AnkiMobile)], 言語, 英語 フランス語 ドイツ語 TTS 読み上げ
https://ankiweb.net/shared/info/697716450[救急診療に役立つ暗記メモ集], 科学技術, 医学 医療
https://ankiweb.net/shared/info/1205685053[GitHubチートシート], 科学技術, 情報 バージョン管理 プログラミング
https://ankiweb.net/shared/info/1880478902[航空用語集], 科学技術, 英語 略語 航空 交通
https://ankiweb.net/shared/info/1112109660[数え方・数助詞], 言語, 国語 数助詞
https://ankiweb.net/shared/info/329800646[変体仮名 Hentaigana Variant Kana], 言語, 国語 古文 かな 変体仮名
https://ankiweb.net/shared/info/587958922[Man'yougana 万葉仮名], 言語, 国語 古文 かな 万葉仮名
https://ankiweb.net/shared/info/69487830[日本史資料 十七条憲法], 人文社会, 歴史 日本史 古文 政治 法律
https://ankiweb.net/shared/info/1639232676[日本史資料 武家諸法度], 人文社会, 歴史 日本史 古文 政治 法律
https://ankiweb.net/shared/info/69487830[日本史資料 五箇条の御誓文], 人文社会, 歴史 日本史 古文 政治 法律
https://ankiweb.net/shared/info/25909930[宮内庁用語集], 人文社会, 国語 儀式 漢字
https://ankiweb.net/shared/info/818749478[歌舞伎の演目名], 人文社会, 日本史 演劇 漢字
https://ankiweb.net/shared/info/333780058[重要古文単語315], 言語, 国語 古文
https://ankiweb.net/shared/info/641220595[古文単語], 言語, 国語 古文
https://ankiweb.net/shared/info/643386433[難読漢字（一般）], 言語, 国語 漢字
https://ankiweb.net/shared/info/1432056637[難読漢字（昆虫、動物、鳥類、爬虫類の名前）], 言語, 国語 漢字
https://ankiweb.net/shared/info/1286270423[難読漢字（植物、果実、野菜の名前）], 言語, 国語 漢字
https://ankiweb.net/shared/info/458314799[難読漢字（物、職業、色の名前）], 言語, 国語 漢字
https://ankiweb.net/shared/info/538946132[難読漢字（魚類、水生動物の名前）], 言語, 国語 漢字
https://ankiweb.net/shared/info/2020347104[まいにちロシア語（入門編）：大人のためのロシア語], 言語, ロシア語 日本語
https://ankiweb.net/shared/info/1653099452[まいにちロシア語（入門編）：繰り返しでマスター！　文法の基礎固め], 言語, ロシア語 日本語
https://ankiweb.net/shared/info/2071573759[まいにちロシア語（応用編）：うきうきルースキー　～私が見たロシア], 言語, ロシア語 日本語
https://ankiweb.net/shared/info/1871538034[身体を表す単語 Russian-Japanese], 言語, ロシア語 日本語
https://ankiweb.net/shared/info/3372203342[簡単フランス語], 言語, フランス語 日本語
https://ankiweb.net/shared/info/1194828453[フランス語単語], 言語, フランス語 日本語
https://ankiweb.net/shared/info/3245135572[Rosetta stone ドイツ語(German) Level 3], 言語, ドイツ語 日本語
https://ankiweb.net/shared/info/485323808[Rosetta stone ドイツ語(German) Level 4], 言語, ドイツ語 日本語
https://ankiweb.net/shared/info/396806471[ポルトガル語ー日本語], 言語, ポルトガル語 日本語
https://ankiweb.net/shared/info/1981573963[ポルトガル語ー日本語 複数形], 言語, ポルトガル語 日本語
https://ankiweb.net/shared/info/1785823362[ポルトガル語ー日本語p], 言語, ポルトガル語 日本語
https://ankiweb.net/shared/info/788807830[ソマリ語], 言語, ソマリ語 日本語
https://ankiweb.net/shared/info/2946080634[日本人の為のペルシア語], 言語, ペルシア語 日本語
https://ankiweb.net/shared/info/1252765692[ベトナム語666], 言語, ベトナム語 日本語
https://ankiweb.net/shared/info/625959472[越語], 言語, ベトナム語 日本語
https://ankiweb.net/shared/info/1235147594[越語2700], 言語, ベトナム語 日本語
https://ankiweb.net/shared/info/1238396573[簡単中国語（北京語）], 言語, 中国語 日本語
https://ankiweb.net/shared/info/771647964[簡単韓国語], 言語, 韓国語 日本語
https://ankiweb.net/shared/info/1030183555[旧字体新字体 Kyuujitai Shinjitai], 言語, 国語 漢字
https://ankiweb.net/shared/info/799735887[說文部首：楷體與小篆], 言語, 漢字 説文解字
https://ankiweb.net/shared/info/833115970[十六進数掛け算], 科学技術, 算数 16進 情報
https://ankiweb.net/shared/info/1037174978[電気通信主任技術者_伝送交換設備及び設備管理], 科学技術, 電気 通信 電気通信主任技術者 資格
https://ankiweb.net/shared/info/4091424041[電験三種_法規], 科学技術, 電気 電気主任技術者 資格
https://ankiweb.net/shared/info/1087111583[電験三種_電力], 科学技術, 電気 電気主任技術者 資格
https://ankiweb.net/shared/info/3985963857[電験三種_機械], 科学技術, 電気 電気主任技術者 資格
https://ankiweb.net/shared/info/614725473[公害防止管理者（公害総論）], 科学技術, 環境 公害防止管理者 資格
https://ankiweb.net/shared/info/1585384509[公害管理者試験（振動・騒音概論）], 科学技術, 環境 公害防止管理者 資格
https://ankiweb.net/shared/info/611525897[確定給付企業年金法の法令解釈], 人文社会, 法律
https://ankiweb.net/shared/info/417940470[英語発音聞き取り改善（日本人のための）], 言語, 英語 日本語 発音 音声
https://ankiweb.net/shared/info/676760195[英語Boost! ‐ 200 Common Phrasal Verbs (句動詞・熟語)], 言語, 英語 音声
https://ankiweb.net/shared/info/1503073102[TOEIC Vocab - English for Japanese - 日本人のための英語コース], 言語, 英語 日本語 TOEIC 検定 画像
https://ankiweb.net/shared/info/258609336[英単語 頻出順 15000語 Level 1 （1－2000）], 言語, 英語 日本語
https://ankiweb.net/shared/info/1924742385[英単語 頻出順 15000語 Level 2 （2001－3000）], 言語, 英語 日本語
https://ankiweb.net/shared/info/226773917[Duo3.0 Tango], 言語, 英語 日本語
https://ankiweb.net/shared/info/159860789[中学英語(English Japanese)], 言語, 英語 日本語
https://ankiweb.net/shared/info/1955159956[TARGET ターゲット 1400 頻出単語 1-1100 English->Japanese], 言語, 英語 日本語
https://ankiweb.net/shared/info/1794720435[GRE Quant英単語], 言語, 英語 日本語 GRE 数的推論 度量衡 検定
https://ankiweb.net/shared/info/2041494066[800ベーシック英単語[CC4.0\]], 言語, 英語 日本語 ベーシック・イングリッシュ
https://ankiweb.net/shared/info/333469572[Books of the Bible in Japanese], 言語, 英語 日本語 宗教 聖書
https://ankiweb.net/shared/info/87825824[LSI Japanisch Aufbaukurs], 言語, ドイツ語 日本語
https://ankiweb.net/shared/info/1871575935[日本語会話・和独 Japanisch Konversation・Japanisch-Deutsch], 言語, ドイツ語 日本語
https://ankiweb.net/shared/info/3239288653[毎日１５分の漢字練習], 言語, フランス語 日本語
https://ankiweb.net/shared/info/1594205371[Hindi-Japanese 200], 言語, ヒンディー語 日本語
https://ankiweb.net/shared/info/113704501[Japanese-Hindi 200], 言語, ヒンディー語 日本語
https://ankiweb.net/shared/info/1364084349[Bộ Thủ Chữ Hán (Tiếng Nhật)], 言語, ベトナム語 日本語
https://ankiweb.net/shared/info/2095212688[Hán Tự Thường Dùng (Tiếng Nhật)], 言語, ベトナム語 日本語
https://ankiweb.net/shared/info/1781457420[Japonština LEDA], 言語, チェコ語 日本語
https://ankiweb.net/shared/info/231402903[Polski-japonski by Adam], 言語, ポーランド語 日本語
https://ankiweb.net/shared/info/398382772[Yhdyssanoja Basic Kanji book 2 (Finnish/Japanese)], 言語, フィンランド語 日本語
https://ankiweb.net/shared/info/1384794163[Vocaboli ed espressioni giapponesi], 言語, イタリア語 日本語
https://ankiweb.net/shared/info/4036197163[Italiano-Giapponese], 言語, イタリア語 日本語
https://ankiweb.net/shared/info/1056471432[kotoba], 言語, スペイン語 日本語
"https://ankiweb.net/shared/info/93980248[Japanese everyday words and phrases, translated into Russian]", 言語, ロシア語 日本語 音声
https://ankiweb.net/shared/info/794286705[Выражения 1 урока An Integrated Approach to Intermediate Jap], 言語, ロシア語 日本語
https://ankiweb.net/shared/info/196511944[Выражения 6 урока An Integrated Approach to Intermediate Jap], 言語, ロシア語 日本語
https://ankiweb.net/shared/info/2872379547[慣用句(あ行)　Идиоматические выражения (а-ряд)(rus)], 言語, ロシア語 日本語
https://ankiweb.net/shared/info/2447397931[Japanisch/Deutsch Vokabular I und II], 言語, ドイツ語 日本語
https://ankiweb.net/shared/info/249991587[Japanisch/Deutsch Vokabular II und III], 言語, ドイツ語 日本語
https://ankiweb.net/shared/info/1625541380[Health and Medical Pictures with English and Japanese], 科学技術, 術語 英語 日本語 医学 医療
https://ankiweb.net/shared/info/1082920264[Japanese Radiological Terms], 科学技術, 術語 医学 医療 放射線 英語 日本語
https://ankiweb.net/shared/info/214864764[Japanese Math Pictures], 科学技術, 術語 英語 日本語 数学 算数
https://ankiweb.net/shared/info/63102099[Japanese Programming], 科学技術, 術語 英語 日本語 プログラミング 情報
https://ankiweb.net/shared/info/1944071542[Japanese and English Fruit Pictures], 言語, 英語 日本語 果物 フルーツ 画像
https://ankiweb.net/shared/info/2107766673[Japanese and English School Pictures], 言語, 英語 日本語 学校 教室 画像
https://ankiweb.net/shared/info/414459136[Japanese Counters], 言語, 英語 日本語 数助詞
https://ankiweb.net/shared/info/1771382918[Japanese Counters], 言語, 英語 日本語 数助詞
https://ankiweb.net/shared/info/1036098926[Japanese Counters], 言語, 英語 日本語 数助詞
https://ankiweb.net/shared/info/115255341[Japanese Counting Systems Version 1.01 (mostly JTMW)], 言語, 英語 日本語 数助詞
https://ankiweb.net/shared/info/188437368[Japanese Newspaper 4560], 言語, 英語 日本語 新聞 報道 ニュース
https://ankiweb.net/shared/info/1073450896[Japanese Newspaper 4560 Additional News], 言語, 英語 日本語 新聞 報道 ニュース
https://ankiweb.net/shared/info/135266511[Japanese signs], 言語, 英語 日本語 標識 ピクトグラム 画像
"https://ankiweb.net/shared/info/2754914665[55k WordNet Definitions & Sentences (Monolingual, Bilingual)]", 言語, 英語 日本語
https://ankiweb.net/shared/info/615343093[sentenças em japonês], 言語, ポルトガル語 日本語
https://ankiweb.net/shared/info/651475745[słówka japońskie], 言語, ポーランド語 日本語
https://ankiweb.net/shared/info/224108184[Vocabulaire Japonais-Français], 言語, フランス語 日本語
https://ankiweb.net/shared/info/722824598[Vocabulaire français-japonais], 言語, フランス語 日本語
https://ankiweb.net/shared/info/1215022603[Great works of art], 人文社会, 英語 美術 絵画 歴史 画像
https://ankiweb.net/shared/info/311374406[Classical Music Themes - Re-uploaded], 人文社会, 英語 音楽 歴史 音源
https://ankiweb.net/shared/info/58419656[Notes of the chromatic scale], 人文社会, 英語 音楽 半音階 音源
https://ankiweb.net/shared/info/946752090[Chord Symbols to piano keys], 人文社会, 音楽 ピアノ 和音 コード キー 画像
https://ankiweb.net/shared/info/395734601[Guitar Chords With Sound by ReinOwader], 人文社会, 音楽 ギター 和音 コード 音源
"https://ankiweb.net/shared/info/1646233599[Birds of Great Britain, with images and sounds]", 科学技術, 生物 分類学 鳥類 鳴き声 英語 画像 音源
"https://ankiweb.net/shared/info/940243165[Dutch birds -- sounds, appearance and taxonomy]", 科学技術, 生物 分類学 鳥類 鳴き声 英語 オランダ語 画像 音源
https://ankiweb.net/shared/info/1680286867[Multiplication Table 2x1 through 20x20 Spreadsheet-built], 科学技術, 算数 掛け算
https://ankiweb.net/shared/info/715012449[2-digit Times Table], 科学技術, 算数 掛け算
https://ankiweb.net/shared/info/1546703997[Mental Arithmetic Practice], 科学技術, 算数 暗算
https://ankiweb.net/shared/info/405506694[Hexadecimal Multiplication Table], 科学技術, 算数 掛け算 16進 情報
https://ankiweb.net/shared/info/736754132[rot13], 科学技術, 情報 暗号 ROT13
https://ankiweb.net/shared/info/1975673825[Electronics: Resistor Color Coding], 科学技術, 電子 抵抗 カラーコード
https://ankiweb.net/shared/info/1291257745[Geography - Oceans & Seas], 科学技術, 地理 英語 地図 画像
https://ankiweb.net/shared/info/2263258759[Countries of the World], 科学技術, 地理 英語 統計 GDP 人口 通貨 地図 画像
https://ankiweb.net/shared/info/3066506982[Chinese provinces and more], 科学技術, 地理 英語 中国 ピンイン 語源 地図 画像
https://ankiweb.net/shared/info/1874254267[Latitudes and longitudes of some major cities], 科学技術, 地理 経度 緯度 英語
https://ankiweb.net/shared/info/2343964336[Amino acids study deck], 科学技術, 生化学 英語 アミノ酸
https://ankiweb.net/shared/info/274734459[Amino Acid Flashcards], 科学技術, 生化学 英語 アミノ酸 画像
"https://ankiweb.net/shared/info/129986190[Chemical elements — number, name, symbol, mass]", 科学技術, 化学 英語 元素 陽子数 原子量
https://ankiweb.net/shared/info/275584315[Perodic table with atomic data], 科学技術, 化学 英語 ドイツ語 元素 周期表 融点 電子配置
https://ankiweb.net/shared/info/1472635709[Ashtanga Yoga], 科学技術, ヨガ アシュタンガ 英語 サンスクリット アサナ 画像
https://ankiweb.net/shared/info/441595417[Physical Exam: Heart Sounds], 科学技術, 医学 医療 心音 英語 音源
https://ankiweb.net/shared/info/1475716870[Mathematical terms], 科学技術, 術語 英語 数学 算数
https://ankiweb.net/shared/info/1085268504[American english pronunciation], 言語, 英語 発音 音声
https://ankiweb.net/shared/info/168692952[Pronunciation practice phonetics (US accent+extra UK) M.F], 言語, 英語 発音 音声
https://ankiweb.net/shared/info/644151027[Portuguese Phrase Book (Continental pronunciation)], 言語, ポルトガル語 発音 音声
https://ankiweb.net/shared/info/428194897[Quranic Arabic Verses word for word SIA (+ audio)], 人文社会, アラビア語 宗教 コーラン 音声
https://ankiweb.net/shared/info/3396002907[Russian Alphabet with Handwritten and Print fonts and sounds], 言語, ロシア語 発音 キリル文字 音声
https://ankiweb.net/shared/info/534801471[Visual Spanish Plus Sound Files from Forvo], 言語, スペイン語 音声
https://ankiweb.net/shared/info/629972372[French 500 coloured words with pictures and audio], 言語, フランス語 画像 音声
https://ankiweb.net/shared/info/1529958967[Norwegian Sentences with Audio], 言語, ノルウェー語 音声
"https://ankiweb.net/shared/info/822208674[Top 5000 - 1,395 Russian Verbs +audio +perfective +conjugati]", 言語, ロシア語 音声
https://ankiweb.net/shared/info/733910527[500 English words(with pictures and audio)], 言語, 英語 画像 音声
https://ankiweb.net/shared/info/1693270835[German FSI Vocab & Basic Sentences (with audio)], 言語, ドイツ語 音声
https://ankiweb.net/shared/info/124854924[FSI Hungarian I Vocab & Basic Sentences (with audio)], 言語, ハンガリー語 音声
https://ankiweb.net/shared/info/1875520915[FSI II Hungarian Basic Sentences (with audio)], 言語, ハンガリー語 音声
https://ankiweb.net/shared/info/2530965591[Hangul (Korean Alphabet)], 言語, 韓国語 ハングル 音声
https://ankiweb.net/shared/info/281628775[Norwegian with Audio], 言語, ノルウェー語 音声
https://ankiweb.net/shared/info/1126003944[German-English top 1000 words - usage frequency (with audio)], 言語, ドイツ語 音声
https://ankiweb.net/shared/info/3004519841[French Numbers 0-99 - Audio Drill], 言語, フランス語 数字 音声
https://ankiweb.net/shared/info/1836502846[Spanish numbers 1-200 with audio], 言語, スペイン語 数字 音声
https://ankiweb.net/shared/info/1197265380[Spanish numbers 200-400 with audio], 言語, スペイン語 数字 音声
https://ankiweb.net/shared/info/1644949726[Spanish numbers 400-1000 with audio random], 言語, スペイン語 数字 音声
https://ankiweb.net/shared/info/1364481455[US Postal Abbreviations], 言語, 英語 アメリカ 郵便 州 略称
|===================================================

=== 使い方

* 右上検索欄にキーワードを入力すると、情報を絞り込みます。
* 分類列やタグ列の単語をクリックすると、その用語で情報を絞り込みます。
* 左上 [検索条件解除] ボタンを押すと、全ての情報を表示します。
* 見出しをクリックすると、情報を並び替えます。
* 上部のドロップダウンから一度に表示する項目数を選択できます。

=== 注意事項

* このデータは、AnkiWeb 共有単語帳の内容を自動的に反映したものではありません。
* 個人的な視点に基づいて選択したデータであって、AnkiWeb 登録の日本語単語帳の一部です。
* 外国語がネイティブの方向けの日本語教材の中に、カードのデザインを工夫すれば、日本人向けの教材として使える物も手録しました。

=== 共有単語帳を使う時の参考に

* 共有単語帳の使い方は、link:/how-to-use-shared-resources/[Ankiの共有リソースを使ってみる]をご覧下さい。

* 共有単語帳の作り方や AnkiWeb への登録方法は、link:/how-to-share-anki-decks/[Anki単語帳を共有する方法]をご覧下さい。

* Anki の使い方に慣れた方に向けて、共有単語帳利用の注意点をlink:/anki-learning-with-shared-decks/[Anki 共有単語帳の学び方]にまとめています。

== 共有単語帳への検索リンク集

更に詳しく AnkiWeb の登録内容を調べるために、日本語での分類項目に対応する検索リンクをまとめました。
日本語の説明がなくても図や音声など役立つデータを含んでいる場合もありますので、英語キーワードもあわせて紹介します。

=== 注意事項 

* タイトルやタグに日本語が使われていれば、日本語を母語とする人を対象としたコンテンツだろうと判断しています。一つ一つの単語帳を確認した訳ではないことはご容赦ください。

* AnkiWeb の共有単語帳検索の対象は、タイトル (Title) と単語帳登録時に設定するタグ (Tags; ユーザーからは見えません) を対象としています。それぞれの単語帳の説明 (Description) は現時点では対象となっていません。

=== 言語

[frame="topbot",grid="rows",cols="2,3",width="",options="header",role="table table-striped table-bordered  table-hover"]
|====
|日本語キーワード|英語キーワード
|link:https://ankiweb.net/shared/decks/%E6%97%A5%E6%9C%AC%E8%AA%9E[日本語], link:https://ankiweb.net/shared/decks/%E5%9B%BD%E8%AA%9E[国語],  link:https://ankiweb.net/shared/decks/%E6%BC%A2%E5%AD%97[漢字],  link:https://ankiweb.net/shared/decks/%E4%BB%AE%E5%90%8D[仮名], link:https://ankiweb.net/shared/decks/%E5%8F%A4%E6%96%87[古文], link:https://ankiweb.net/shared/decks/%E9%83%A8%E9%A6%96[部首]| link:https://ankiweb.net/shared/decks/japanese/[Japanese], link:https://ankiweb.net/shared/decks/kanji[Kanji]
|アラビア語|link:https://ankiweb.net/shared/decks/arabic[Arabic]
|イタリア語|link:https://ankiweb.net/shared/decks/Italian[Italian]
|ウクライナ語|link:https://ankiweb.net/shared/decks/Ukrainian[Ukrainian]
|link:https://ankiweb.net/shared/decks/%E8%8B%B1%E8%AA%9E[英語], link:https://ankiweb.net/shared/decks/%E8%8B%B1%E6%A4%9C[英検]|link:https://ankiweb.net/shared/decks/english[English],link:https://ankiweb.net/shared/decks/TOEFL[TOEFL], link:https://ankiweb.net/shared/decks/TOEIC[TOEIC], link:https://ankiweb.net/shared/decks/IELTS[IELTS], link:https://ankiweb.net/shared/decks/CAE[CAE]
|link:https://ankiweb.net/shared/decks/%E9%9F%93%E5%9B%BD%E8%AA%9E[韓国語]|link:https://ankiweb.net/shared/decks/korean[Korean]
|ギリシャ語|link:https://ankiweb.net/shared/decks/greek[Greek]
|クメール語|link:https://ankiweb.net/shared/decks/Khmer[Khmer]
|サンスクリット|link:https://ankiweb.net/shared/decks/sanskrit[Sanskrit]
|スペイン語|link:https://ankiweb.net/shared/decks/spanish[Spanish]
|link:https://ankiweb.net/shared/decks/%E4%B8%AD%E5%9B%BD%E8%AA%9E[中国語]|link:https://ankiweb.net/shared/decks/chinese[Chinese], link:https://ankiweb.net/shared/decks/mandarin[Mandarin]
|タイ語|link:https://ankiweb.net/shared/decks/Thai[Thai]
|link:https://ankiweb.net/shared/decks/%E3%83%89%E3%82%A4%E3%83%84%E8%AA%9E[ドイツ語]|link:https://ankiweb.net/shared/decks/german[German]
|トルコ語|link:https://ankiweb.net/shared/decks/Turkish[Turkish]
|ヒンディー語|link:https://ankiweb.net/shared/decks/hindi[Hindi]
|link:https://ankiweb.net/shared/decks/%E3%83%95%E3%83%A9%E3%83%B3%E3%82%B9%E8%AA%9E[フランス語]|link:https://ankiweb.net/shared/decks/french[French]
|link:https://ankiweb.net/shared/decks/%E3%83%99%E3%83%88%E3%83%8A%E3%83%A0%E8%AA%9E[ベトナム語]|link:https://ankiweb.net/shared/decks/Vietnamese[Vietnamese]
|ヘブライ語|link:https://ankiweb.net/shared/decks/Hebrew[Hebrew]
|link:https://ankiweb.net/shared/decks/%E3%83%9A%E3%83%AB%E3%82%B7%E3%82%A2%E8%AA%9E[ペルシャ語]|link:https://ankiweb.net/shared/decks/persian[Persian]
|ベンガル語|link:https://ankiweb.net/shared/decks/bengal[Bengal]
|ポーランド語|link:https://ankiweb.net/shared/decks/Polish[Polish]
|link:https://ankiweb.net/shared/decks/%E3%83%9D%E3%83%AB%E3%83%88%E3%82%AC%E3%83%AB%E8%AA%9E[ポルトガル語]|link:https://ankiweb.net/shared/decks/portugues[Portugues]
|マラティ語|link:https://ankiweb.net/shared/decks/Marathi[Marathi]
|マレー語|link:https://ankiweb.net/shared/decks/malay[Malay]
|link:https://ankiweb.net/shared/decks/%E3%83%AD%E3%82%B7%E3%82%A2%E8%AA%9E[ロシア語]|link:https://ankiweb.net/shared/decks/russian[Russian]
|ラテン語|link:https://ankiweb.net/shared/decks/latin[Latin]
|====

=== 人文社会

[frame="topbot",grid="rows",cols="2,3",width="",options="header",role="table table-striped table-bordered  table-hover"]
|====
|日本語キーワード|英語キーワード
|哲学|link:https://ankiweb.net/shared/decks/philosophy[Philosophy]
|聖書|link:https://ankiweb.net/shared/decks/bible[Bible]
|コーラン|link:https://ankiweb.net/shared/decks/quran[Quran]
|仏教|link:https://ankiweb.net/shared/decks/buddha[Buddha], link:https://ankiweb.net/shared/decks/buddhism[Buddhism]
|心理|link:https://ankiweb.net/shared/decks/Psychology[Psychology]
|言語|link:https://ankiweb.net/shared/decks/linguistics[Linguistics]
|link:https://ankiweb.net/shared/decks/%E6%AD%B4%E5%8F%B2[歴史]|link:https://ankiweb.net/shared/decks/history[History], link:https://ankiweb.net/shared/decks/history%20of%20japan[History of Japan]
|link:https://ankiweb.net/shared/decks/%E5%9C%B0%E7%90%86[地理]|link:https://ankiweb.net/shared/decks/Geography[Geography]
|音楽|link:https://ankiweb.net/shared/decks/music[Music]
|link:https://ankiweb.net/shared/decks/%E6%95%99%E8%82%B2[教育]|link:https://ankiweb.net/shared/decks/education[Education]
|学力試験|link:https://ankiweb.net/shared/decks/GCSE[GCSE], link:https://ankiweb.net/shared/decks/AQA[AQA], link:https://ankiweb.net/shared/decks/sat%20vocab[SAT Vocab]ulary, link:https://ankiweb.net/shared/decks/gre%20vocab[GRE Vocab]ulary
|link:https://ankiweb.net/shared/decks/%E6%B3%95%E5%BE%8B[法律], link:https://ankiweb.net/shared/decks/%E6%B3%95%E4%BB%A4[法令]|link:https://ankiweb.net/shared/decks/law[Law]
|link:https://ankiweb.net/shared/decks/%E6%94%BF%E6%B2%BB[政治]|link:https://ankiweb.net/shared/decks/politics[Politics]
|経済|link:https://ankiweb.net/shared/decks/Economics[Economics]
|会計|link:https://ankiweb.net/shared/decks/CPA[CPA]
|マーケティング|link:https://ankiweb.net/shared/decks/Marketing[Marketing]
|プロジェクト管理|link:https://ankiweb.net/shared/decks/Project%20Management[Project Management], link:https://ankiweb.net/shared/decks/PMBOK[PMBOK]
|====

=== 科学技術

[frame="topbot",grid="rows",cols="2,3",width="",options="header",role="table table-striped table-bordered  table-hover"]
|====
|日本語キーワード|英語キーワード
|数学|link:https://ankiweb.net/shared/decks/math[Math]
|統計|link:https://ankiweb.net/shared/decks/statistics[Statistics]
|物理|link:https://ankiweb.net/shared/decks/physics[Physics]
|化学|link:https://ankiweb.net/shared/decks/chemistry[Chemistry]
|生物|link:https://ankiweb.net/shared/decks/biology[Biology]
|解剖学|link:https://ankiweb.net/shared/decks/anatomy[Anatomy]
|生理学|link:https://ankiweb.net/shared/decks/Physiology[Physiology]
|link:https://ankiweb.net/shared/decks/%E5%8C%BB%E5%AD%A6[医学], link:https://ankiweb.net/shared/decks/%E5%8C%BB%E7%99%82[医療]|link:https://ankiweb.net/shared/decks/medicine[Medicine], link:https://ankiweb.net/shared/decks/medical[Medical], link:https://ankiweb.net/shared/decks/USMLE[USMLE]
|病理学|link:https://ankiweb.net/shared/decks/pathology[Pathology]
|歯学|link:https://ankiweb.net/shared/decks/Dentistry[Dentistry], link:https://ankiweb.net/shared/decks/dental[Dental]
|薬学|link:https://ankiweb.net/shared/decks/Pharmacology[Pharmacology],link:https://ankiweb.net/shared/decks/drug[Drug]
|獣医学|link:https://ankiweb.net/shared/decks/Veterinary[Veterinary]
|エンジニアリング|link:https://ankiweb.net/shared/decks/Engineering[Engineering]
|建築|link:https://ankiweb.net/shared/decks/Architecture[Architecture]
|情報|link:https://ankiweb.net/shared/decks/software[Software], link:https://ankiweb.net/shared/decks/Programming[Programming], link:https://ankiweb.net/shared/decks/network[Network]
|金属|link:https://ankiweb.net/shared/decks/metal[Metal]
|デザイン|link:https://ankiweb.net/shared/decks/design[Design]
|環境, link:https://ankiweb.net/shared/decks/%E5%85%AC%E5%AE%B3[公害]|link:https://ankiweb.net/shared/decks/environment[Environment]
|====

== 更新情報

2015/02/17: 初出

2015/02/26: 追加: 人文社会、科学技術

2016/01/27: 最新情報にあわせて全面更新

2016/02/05: 単語帳検索画面を追加
